### ISSUE TITLE
Need User agent switcher

### ISSUE THREAD

**Issue by schaengel** [guardianproject/tor-browser#12]
I aprreciate the efforts put in this browser and it makes for a real privacy browser. But every time a HTTP request is sent we will be leaking the browser identity.

It needs a user agent switcher which is on by default  to randomise the agent so that users are not tracked.

**Comment by pgerber** [comment]
Tor Browser doesn't attempt to hide the fact that you're using Tor browser. Attempting to hide it would be futile. Tor Browser disables certain features, adds others, traffic is relayed through Tor and so on. This makes it very easy to figure out that you're using Tor Browser, independent of the User-Agent string.

From [The Design and Implementation of the Tor Browser](https://www.torproject.org/projects/torbrowser/design/#fingerprinting-linkability):

> Due to vast differences in feature set and implementation behavior even between different (minor) versions of the same browser, browser vendor and version differences are simply not possible to conceal in any realistic way. It is only possible to minimize the differences among different installations of the same browser vendor and version. We make no effort to mimic any other major browser vendor, and in fact most of our fingerprinting defenses serve to differentiate Tor Browser users from normal Firefox users. Because of this, any study that lumps browser vendor and version differences into its analysis of the fingerprintability of a population is largely useless for evaluating either attacks or defenses. Unfortunately, this includes popular large-scale studies such as Panopticlick and Am I Unique.
