### ISSUE TITLE
Orfox-Fennec is infested with Google-Trackers/Backdoors 

### ISSUE THREAD

**Issue by Wasnix** [guardianproject/tor-browser#18]
Orfox-Fennec is infested with Google-Trackers/Backdoors. I checked the apk-files of Orfox-1.5.x-Fennec from offical Guardian download: https://guardianproject.info/releases/

You can verify this with eg. ClassyShark3xodus from f-droid: https://f-droid.org/de/packages/com.oF2pks.classyshark3xodus/  (see screenshot)

All versions contains 4 different trackers:
  Adjust
  Google Ads
  Google Doubleclick
  Google Firebase Analytics
  
It's an absolute no-go! Each Orfox user gets an unique identifier and is no longer anonymous with such builtin spyware.

You should remove infested files from download area until this bugs are fixed.

![screenshot](https://user-images.githubusercontent.com/8307605/50564626-aa625480-0d26-11e9-89dd-15d575313360.jpg)

**Comment by n8fr8** [comment]
These are part of the Mozilla Firefox codebase we inherit. It was too complicated to remove all of the code dependencies. While the bytecode is compiled in, they are all fully deactivated. As part of our testing we check for outbound traffic from the app, to ensure there are no unexpected callbacks from trackers. We have addressed this publicly in other threads and places.

Further development of Orfox is being done by the Tor Browser team, so if you have further objections or input, please post it on their tracker or discuss it on IRC, mailing lists,etc: 
https://trac.torproject.org/projects/tor
