### ISSUE TITLE
[Bug] Addons are not being installed in Android 

### ISSUE THREAD

**Issue by mystic-githuber** [guardianproject/tor-browser#19]
Even though new addons is shown to be installed after installing, there are not enabled when browsing. The hamburger menu with addons subsection doesn't show the new installed addons. 

Android version number 10.5.5 (91.2.0).

**Comment by n8fr8** [comment]
this project is now closed. The Tor Project is now directly managing Tor Browser for Android.

https://gitlab.torproject.org/explore/projects/trending
